systems:
  configs:
    SYSTEM_4GA:
      datasources:
        PRIMARY:
          url: jdbc:mysql://localhost:3306/pm_access?useSSL=false&serverTimezone=UTC
          username: root
          password: nam123
          driverClassName: com.mysql.cj.jdbc.Driver
          maximumPoolSize: 15
          connectionTimeoutMs: 60000
        CLICKHOUSE:
          url: jdbc:clickhouse://localhost:8123/pm_access
          username: default
          password: nam123
          driverClassName: com.clickhouse.jdbc.ClickHouseDriver
          maximumPoolSize: 10
          connectionTimeoutMs: 60000
      primaryDatasource: PRIMARY
      deploy: false
      custom:
        isUsingClickhouse: true
        isUsingMySQL: true
        consumerThreads: 30
        clickHouseDatabase: pm_access_4g
        isAutoAddingColumn: false
        serviceName: 4GA
