systems:
  configs:
    SYSTEM_ONT:
      datasources:
        PRIMARY:
          url: jdbc:mysql://localhost:3306/pm_api_ont?useSSL=false&serverTimezone=UTC
          username: root
          password: nam123
          driverClassName: com.mysql.cj.jdbc.Driver
          maximumPoolSize: 15
          connectionTimeoutMs: 60000
        CLICKHOUSE:
          url: jdbc:clickhouse://localhost:8123/pm_api_ont
          username: default
          password: nam123
          driverClassName: com.clickhouse.jdbc.ClickHouseDriver
          maximumPoolSize: 10
          connectionTimeoutMs: 60000
      primaryDatasource: PRIMARY
      deploy: false
      custom:
        isUsingClickhouse: true
        isUsingMySQL: true
        consumerThreads: 30
        clickHouseDatabase: pm_ont
        isAutoAddingColumn: false
        serviceName: ACS
